config/routes.rb
Rails.application.routes.draw do
  devise_for :companies
  resources :departments do
    resources :employees
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # as :company do
  #   get 'login', to: 'devise/sessions#new'
  # end

  root to:"departments#index"

 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :departments, dependent: :destroy
end

app/models/department.rb
class Department < ApplicationRecord
    has_many :employees,dependent: :destroy
    belongs_to :company
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :department
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_company!
  # GET /departments
  # GET /departments.json
  def index
    @departments = Department.where(company_id: current_company.id)
    @department = Department.new
    @employees = Employee.all

    # @cantidad = Department.find(params[:id]).employees.length

  end

  # GET /departments/1
  # GET /departments/1.json
    def show
      self.new
      render(:action => 'new')
    end

  # GET /departments/new
  def new
    @department = Department.new
    # @employee = Employee.find(params[:employee_id])
  end

  # GET /departments/1/edit
  def edit
    @departments = Department.where(company_id: current_company.id)
    @employee = Employee.all
    @employees = Employee.all

  end

  # POST /departments
  # POST /departments.json
  def create
    @department = Department.new(department_params.merge!({company_id: current_company.id}))
    
    respond_to do |format|
      if @department.save
        format.html { redirect_to departments_path, notice: 'El departamento fue creado exitosamente' }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1
  # PATCH/PUT /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to departments_path, notice: 'El departamento fue editado exitosamente' }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department.destroy
    respond_to do |format|
      format.html { redirect_to departments_url, notice: 'El departamento fue borrado exitosamente' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def department_params
      params.require(:department).permit(:name)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  # before_action :assign_department

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.where(department_id: params[:department_id])
    @employee = Employee.new
    @department = Department.find(params[:department_id])
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @department = Department.find(params[:department_id])
  end

  # GET /employees/new
  def new
    @employee = Employee.new
    @department = Department.find(params[:department_id])
  end

  # GET /employees/1/edit
  def edit
    @employees = Employee.where(department_id: params[:department_id])
    @department = Department.find(params[:department_id])
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)
    @department = Department.find(params[:department_id])
    # @employee = @department.build_employee(employee_params.merge!{:department_id})

    respond_to do |format|
      if @employee.save
        format.html { redirect_to department_employees_path, notice: 'El empleado fue creado exitosamente' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to department_employees_path, notice: 'El empleado fue editado exitosamente' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to department_employees_path, notice: 'El empleado fue borrado exitosamente' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # def assign_department
    #   @department = Department.find(params[:department_id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name, :last_name, :dni, :cellphone, :bank, :account, :number_account, :phone, :emergency_phone, :department_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/departments/_form.html.erb
<div class="margen text-rigth">
  <%= form_with(model: department, local: true ,html: {class: "form-signin"}) do |form| %>
    <% if department.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(department.errors.count, "error") %> prohibited this department from being saved:</h2>

        <ul>
        <% department.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :Nombre_del_departamento  , class: 'ezquinado3' %>
      <%= form.text_field :name, id: :department_name,class: 'form-control' %>
    </div>

    <div class="actions haha">
      <%= form.submit "Guardar" ,class:'btn btn-lg btn-primary btn-block hola' %>
    </div>
</div>
  <% end %>

app/views/departments/edit.html.erb
<div class="row margen">
  <%= form_tag departments_path, method: 'get', class: 'col-12 navbar-form', role: 'search' do %>
    <div class="input-group">
     <%= text_field_tag :query, params[:query], size: 150, placeholder: "Search", class: "col-10 form-control search"%>
     <%= submit_tag '  ', class: 'col-1btn btn-primary btn-sm search' %><i class="fas fa-search"></i>
     <%= link_to "Cerrar sesion", destroy_company_session_path, method: :delete, class: "col-1 btn btn-danger" %>
    </div>
  <% end %>
</div>
<% if notice %>
<div class="alert alert-success alert-dismissable success">
  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
  <h6 id="notice"><%= notice %></h6>
</div>
<% end %>
<h1 class="solito">Editar departmento</h1>

<%= render 'form', department: @department %>
<h3 class="alrincon">Departmentos</h3>


<table class="table margen">
  <thead>
    <tr>
      <th>Nombre del departamento</th>
      <th>Cantidad de empleados</th>
      <th colspan="9">&nbsp&nbsp&nbsp&nbsp&nbspAcciones</th>
    </tr>
  </thead>

  <tbody>
    <% @departments.each do |department| %>
      <tr>
        <td><%= link_to department.name, department_employees_path(department)%></td>
        <td class="text-center"><%= @employees.where(:department_id =>department.id).length  %></td>
        <td><%= link_to department_employees_path(department) do %>
          <i class="fas fa-users"></i>
        <% end %>
        </td>
        <td><%= link_to edit_department_path(department) do %>
          <i class="fas fa-pencil-alt"></i>
        <% end %>
        </td>
        <td><%= link_to department, method: :delete, data: { confirm: 'Are you sure?' } do %>
          <i class="fas fa-trash"></i>
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/departments/index.html.erb
<div class="row margen">
  <%= form_tag departments_path, method: 'get', class: 'col-12 navbar-form', role: 'search' do %>
    <div class="input-group">
     <%= text_field_tag :query, params[:query], size: 150, placeholder: "Search", class: "col-10 form-control search"%>
     <%= submit_tag '  ', class: 'col-1btn btn-primary btn-sm search' %><i class="fas fa-search"></i>
     <%= link_to "Cerrar sesion", destroy_company_session_path, method: :delete, class: "col-1 btn btn-danger" %>
    </div>
  <% end %>
</div>
<% if notice %>
<div class="alert alert-success alert-dismissable success">
  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
  <h6 id="notice"><%= notice %></h6>
</div>
<% end %>
<h1 class="solito">Nuevo departmento</h1>

<%= render 'form', department: @department %>
<h3 class="alrincon">Departmentos</h3>

<% if @departments.empty? %>
  <div class="images text-center card">
    <h4 class="abajito">Aun no hay departamentos.</h4>
    <h7 class="masabajo">Puedes crear tu primer departamento utilizando el siguiente formulario.</h7>
  </div>
<% else  %>
  <table class="table margen">
    <thead>
      <tr>
        <th>Nombre del departamento</th>
        <th>Cantidad de empleados</th>
        <th colspan="6">&nbsp&nbsp&nbsp&nbsp&nbspAcciones</th>
      </tr>
    </thead>

    <tbody>
      <% @departments.each do |department| %>
        <tr>
          <td><%= link_to department.name, department_employees_path(department)%></td>
          <td class="text-center"><%= @employees.where(:department_id =>department.id).length  %></td>
          <td><%= link_to "<i class='fas fa-users'></i>".html_safe, department_employees_path(department) %>
          </td>
          <td><%= link_to edit_department_path(department) do %>
            <i class="fas fa-pencil-alt"></i>
          <% end %>
          </td>
          <td><%= link_to department, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <i class="fas fa-trash"></i>
          <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/departments/new.html.erb
<h1>New Department</h1>

<%= render 'form', department: @department %>

<%= link_to 'Back', departments_path %>

app/views/departments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @department.name %>
</p>

<%= link_to 'Edit', edit_department_path(@department) %> |
<%= link_to 'Back', departments_path %>

app/views/employees/_form.html.erb
<div class="margen text-rigth3">
  <%= form_for [@department, @employee],html: {class: "form-signin"} do |form| %>
    <% if @employee.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

        <ul>
        <% employee.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field enlinea">
      <%= form.label :Primer_nombre, class: 'ezquinadoo' %>
      <%= form.text_field :name, id: :employee_name,class: 'form-control' %>
    </div>

    <div class="field enlinea">
      <%= form.label :Apellido , class: 'ezquinadoo1' %>
      <%= form.text_field :last_name, id: :employee_last_name,class: 'form-control' %>
    </div>

    <div class="field enlinea">
      <%= form.label :Cedula , class: 'ezquinadoo2' %>
      <%= form.number_field :dni, id: :employee_dni,class: 'form-control' %>
    </div>

    <div class="field enlinea">
      <%= form.label :Celular , class: 'ezquinadoo3' %>
      <%= form.number_field :cellphone, id: :employee_cellphone,class: 'form-control' %>
    </div>

    <div class="field enlinea2">
      <%= form.label :Correo_electronico , class: 'ezquinadoo4'%>
      <%= form.text_field :bank, id: :employee_bank,class: 'form-control' %>
    </div>

    <div class="field enlinea">
      <%= form.label :Banco , class: 'ezquinadoo5'%>
      <%= form.text_field :bank, id: :employee_bank,class: 'form-control' %>
    </div>

    <div class="field enlinea">
      <%= form.label :Tipo_de_cuenta , class: 'ezquinadoo6' %>
      <%= form.text_field :account, id: :employee_account,class: 'form-control' %>
    </div>

    <div class="field enlinea2">
      <%= form.label :Nro_de_cuenta , class: 'ezquinadoo7' %>
      <%= form.text_field :number_account, id: :employee_number_account,class: 'form-control' %>
    </div>

    <div class="field enlinea">
      <%= form.label :Telefono_fijo , class: 'ezquinadoo8'%>
      <%= form.text_field :phone, id: :employee_phone,class: 'form-control' %>
    </div>

    <div class="field enlinea">
      <%= form.label :Telefono_de_emergencia , class: 'ezquinadoo9' %>
      <%= form.text_field :emergency_phone, id: :employee_emergency_phone,class: 'form-control' %>
    </div>

    <div class="field enlinea">
      <%= form.hidden_field :department_id, :value => params[:department_id] %>
    </div>


    <div class="actions haha">
      <%= form.submit "Guardar",class:'btn btn-lg btn-primary btn-block hola' %>
    </div>
  <% end %>
</div>

app/views/employees/edit.html.erb
<div class="row margen">
  <%= form_tag @employees_path, method: 'get', class: 'col-12 navbar-form', role: 'search' do %>
    <div class="input-group">
     <%= text_field_tag :query, params[:query], size: 150, placeholder: "Search", class: "col-10 form-control search"%>
     <%= submit_tag '  ', class: 'col-1btn btn-primary btn-sm search' %> <i class="fas fa-search"></i>
     <%= link_to "Cerrar sesion", destroy_company_session_path, method: :delete, class: "col-1 btn btn-danger" %>
    </div>
  <% end %>
</div>
<% if notice %>
<div class="alert alert-success alert-dismissable success">
  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
  <h6 id="notice"><%= notice %></h6>
</div>
<% end %>
<h1 class="solito">Editar empleado </h1>

<%= render 'form', employee: [@department, @employee]  %>
<h3 class="alrincon"><%= link_to '‹', departments_path, class:"flechita" %>Empleados de <span class="colorido"><%= @department.name %></span> </h3>


<table class="table margen">
  <thead>
    <tr>
      <th>Cedula</th>
      <th>Nombre</th>
      <th>Celular</th>
      <th colspan="3">Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.dni %></td>
        <td><%= employee.name  %></td>
        <td><%= employee.cellphone  %></td>
        <td><%= %></td>
        <td><%= link_to "/departments/#{@department.id}/employees/#{employee.id}/edit" do %>
          <i class="fas fa-pencil-alt"></i>
        <% end %>
        </td>
        <td><%= link_to "/departments/#{@department.id}/employees/#{employee.id}", method: :delete, data: { confirm: 'Are you sure?' } do %>
          <i class="hola fas fa-trash "></i>
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/employees/index.html.erb
<div class="row margen">
  <%= form_tag @employees_path, method: 'get', class: 'col-12 navbar-form', role: 'search' do %>
    <div class="input-group">
     <%= text_field_tag :query, params[:query], size: 150, placeholder: "Search", class: "col-10 form-control search"%>
     <%= submit_tag '  ', class: 'col-1btn btn-primary btn-sm search' %><i class="fas fa-search"></i>
     <%= link_to "Cerrar sesion", destroy_company_session_path, method: :delete, class: "col-1 btn btn-danger" %>
    </div>
  <% end %>
</div>
<% if notice %>
<div class="alert alert-success alert-dismissable success">
  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
  <h6 id="notice"><%= notice %></h6>
</div>
<% end %>
<h1 class="solito">Nuevo empleado </h1>

<%= render 'form', employee: [@department, @employee]  %>
<h3 class="alrincon"><%= link_to '‹', departments_path, class:"flechita"  %>Empleados de <span class="colorido"><%= @department.name %></span> </h3>

<% if @employees.empty? %>
  <div class="images text-center card">
    <h4 class="abajito">Aun no hay empleados.</h4>
    <h7 class="masabajo">Puedes crear tu primer empleado utilizando el siguiente formulario.</h7>
  </div>
<% else  %>
  <table class="table margen">
    <thead>
      <tr>
        <th>Cedula</th>
        <th>Nombre</th>
        <th>Celular</th>
        <th colspan="3">Acciones</th>
      </tr>
    </thead>

    <tbody>
      <% @employees.each do |employee| %>
        <tr>
          <td><%= employee.dni %></td>
          <td><%= employee.name  %></td>
          <td><%= employee.cellphone  %></td>
          <td><%= %></td>
          <td><%= link_to "/departments/#{@department.id}/employees/#{employee.id}/edit" do %>
            <i class="fas fa-pencil-alt"></i>
          <% end %>
          </td>
          <td><%= link_to "/departments/#{@department.id}/employees/#{employee.id}", method: :delete, data: { confirm: 'Are you sure?' } do %>
            <i class="hola fas fa-trash "></i>
          <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @employee.last_name %>
</p>

<p>
  <strong>Dni:</strong>
  <%= @employee.dni %>
</p>

<p>
  <strong>Cellphone:</strong>
  <%= @employee.cellphone %>
</p>

<p>
  <strong>Bank:</strong>
  <%= @employee.bank %>
</p>

<p>
  <strong>Account:</strong>
  <%= @employee.account %>
</p>

<p>
  <strong>Number account:</strong>
  <%= @employee.number_account %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @employee.phone %>
</p>

<p>
  <strong>Emergency phone:</strong>
  <%= @employee.emergency_phone %>
</p>


<%= link_to 'Edit', edit_department_employee_path(@employee) %> |
<%= link_to 'Back', departments_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Elproyect</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
  </head>

  <body>
  

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <%= yield %>
  </body>
</html>